Switch to github-actions
MetaModels/attribute_langcode pull request #13
Opened 2021-08-01 16:11 UTC by zonky2

Switch to github-actions

2021-08-04 16:10 UTC, discordier requested changes

2021-08-04 16:10 UTC, discordier commented on tests/ContaoManager/PluginTest.php
> +     *
Why? Please revert.

2021-08-04 16:13 UTC, zonky2 commented on tests/ContaoManager/PluginTest.php
> +     *
jess

2021-08-05 06:44 UTC, discordier approved these changes

2023-01-05 16:43 UTC, zonky2 commented
Implemented in MM 2.2

2023-01-05 16:43 UTC, closed without merging